# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

mapping = Mapping.create(symbol: "activity", object_type: "Activity")
mapping = Mapping.create(symbol: "endearment", object_type: "Endearment")
mapping = Mapping.create(symbol: "verb", object_type: "Verb")
mapping = Mapping.create(symbol: "group", object_type: "Group")
template = Pickup.create(text: "Hey, you look like [endearment], let's [activity]!")
template = Pickup.create(text: "Who do you think [verb] more, [group] or [group]?")

Partial.create(object_type:"Endearment", text: "my future ex-girlfriend")
Partial.create(object_type:"Endearment", text: "the one and true love of my life")
Partial.create(object_type:"Endearment", text: "the mother of my future children")
Partial.create(object_type:"Endearment", text: "the girl my mom warned me about")
Partial.create(object_type:"Endearment", text: "my kindergarten sweetheart")
Partial.create(object_type:"Endearment", text: "my elementary school girlfriend")
Partial.create(object_type: "Activity", text: "go hunt for stashes of Nazi gold")
Partial.create(object_type: "Activity", text: "fly to Vegas, lose a bunch of money and get married")
Partial.create(object_type: "Activity", text: "have a dozen kids together")
Partial.create(object_type: "Activity", text: "get into a fight about who keeps the dogs")
Partial.create(object_type: "Activity", text: "go to the amusement park, I will win you a stuffed puppy")
Partial.create(object_type: "Verb", text: "lies")
Partial.create(object_type: "Verb", text: "likes puppies")
Partial.create(object_type: "Verb", text: "enjoys life")
Partial.create(object_type: "Verb", text: "starts fights")
Partial.create(object_type: "Verb", text: "keeps their promises")
Partial.create(object_type: "Group", text: "married men")
Partial.create(object_type: "Group", text: "single women")
Partial.create(object_type: "Group", text: "ninjas")
Partial.create(object_type: "Group", text: "pirates")
Partial.create(object_type: "Group", text: "method actors")
Partial.create(object_type: "Group", text: "runway models")
Partial.create(object_type: "Group", text: "circus clowns")
Partial.create(object_type: "Group", text: "lion tamers")
Partial.create(object_type: "Group", text: "Nebraskan cowboys")
Partial.create(object_type: "Group", text: "Hawaiian surfers")
Partial.create(object_type: "Group", text: "single librarians")
Partial.create(object_type: "Group", text: "retired astronauts")
Partial.create(object_type: "Group", text: "popstars")
